backend:
  name: github
  repo: Andrei-Ciobanu-3PG/netlify-cms-tutorial # Path to your GitHub repository
  branch: master
  base_url: https://netlify-cms-github-oauth-provi.herokuapp.com

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
- name: "landing_pages"
  label: "Landing Pages"
  folder: "landing_pages"
  create: true
  extension: json
  slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
  fields:
    - {name: path, label: Path }
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Subtitle", name: "subtitle", widget: "string"}
    - {label: "Banner", name: "banner", widget: "image"}
    - name: offers
      required: false
      label: Offers
      widget: "list"
      allow_add: true
      fields:
        - {name: offerId, label: "Offer Id", widget: "string"}
        - {name: name, label: "Offer Name", widget: "string"}
        - {name: description, label: "Offer Description", widget: "string"}
        - {name: weekDescription, label: "Week Description", widget: "string"}
        - {name: body, label: "Offer Body", widget: "markdown"}
